### ISSUE TITLE
Unable to `Dev::Patch` to some pages due to invalid access

### ISSUE THREAD

**Issue by Phlarx** [openplanet-nl/issues#1]
(In Turbo and MP4, untested in Next)

I am unable to `Dev::Patch` to a read-only page (read-execute pages work fine) to change some string constants. The error I get is:
```
[           Hooks] [01:44:10]  Unable to patch memory (error 998)
```
Which means `Invalid access to memory location.`

An example of the actual code, for both games, is:
```angelscript
uint64 template = Dev::FindPattern("25 73 25 64 3A 25 2E 32 64 2E 25 2E 32 64 00");
// MP4: template == 0x0000000041672198 (actual address 0x0000000141672198)
// Turbo: template == 0x00000000016C9F58

string bytes_template = Dev::Patch(template, "25 73 25 64 3A 25 2E 32 64 2E 25 2E 33 64 00");
// Unable to patch memory (error 998)
```

(original report in Discord: https://discord.com/channels/276076890714800129/424967293538402334/890134359330410506)

**Comment by codecat** [comment]
This is because the data is in the `.rdata` section, and on Maniaplanet and Turbo, the page's protection remains unchanged. I'd invite you to try this on Next, where the protection flags **are** changed, to confirm that this would indeed fix the problem on MP and Turbo.

**Comment by Phlarx** [comment]
Yes, I can confirm that this does work in Next. The pattern I used as an example no longer exists, but this related example (that appears in all three games) does work:
```angelscript
uint64 template = Dev::FindPattern("25 73 25 64 3A 25 2E 32 64 3A 25 2E 32 64 2E 25 2E 32 64 00");
// Next: template == 0x000000008A890488 (actual address 0x00007FF68A890488)

string bytes_template = Dev::Patch(template, "25 73 25 64 3A 25 2E 32 64 3A 25 2E 32 64 2E 25 2E 33 64 00");
// Success

Dev::Patch(template, bytes_template);
// Success
```
