### ISSUE TITLE
Missing enum for CGameScriptHandlerPlaygroundInterface > CloseInGameMenu and PlayUISound

### ISSUE THREAD

**Issue by glocom** [openplanet-nl/issues#12]
The CGameScriptHandlerPlaygroundInterface > CloseInGameMenu method previously expected the enum parameter EInGameMenuResult, but now it expects UnnamedEnum. This does not work as intended and it should be reverted to the EInGameMenuResult enum.

I noticed the same for the PlayUISound enum, which used to be EUISound.

Reference to the docs: https://next.openplanet.nl/Game/CGameScriptHandlerPlaygroundInterface

**Comment by codecat** [comment]
Thanks! Nadeo's code in this regard is pretty messed up and all over the place. I'm not sure why they made this change. Either way, I have managed to fix this and many of these instances:

![image](https://user-images.githubusercontent.com/136534/140615591-c055482a-0681-4804-bfd4-8cdfa386e6b6.png)
