### ISSUE TITLE
Add feature to rename settings panel generated by RenderSettings()

### ISSUE THREAD

**Issue by RuurdBijlsma** [openplanet-nl/issues#18]
When using `RenderSettings()` to add a custom settings panel, it shows up with the name "Script". As far as I know there's no way to rename this. 

![image](https://user-images.githubusercontent.com/5478546/142094191-22c3f63b-cf07-4f7b-add8-db4637ae91bd.png)

Maybe the `</>` icon can be kept if you want users to know a panel is script generated. Syntax for renaming the panel could be something like so maybe:

```
[Setting category="Advanced Settings"]
void RenderSettings(){
    // render settings
}
```

Feel free to close the issue if you don't think it should be added or it's not worth the extra work.

**Comment by Phlarx** [comment]
A perhaps simpler approach is to use a string-type return value, or an `&out` reference parameter.

All of these would result in only a single panel being available, though, so if we ever wanted to be able to produce multiple script tabs, something else would be needed.

**Comment by codecat** [comment]
Yeah, I kinda like that idea though, but a little modified:

```asc
[SettingsTab name="Advanced settings"]
void RenderAdvancedSettingsTab()
{
  // stuff
}
```

**Comment by codecat** [comment]
I think this will do 👍 

![image](https://user-images.githubusercontent.com/136534/142766427-87f9c0b5-7356-4990-a35b-f7f478b15e85.png)
