### ISSUE TITLE
Enhancement - Add ability to declare plugin preprocessor variables in the info.toml

### ISSUE THREAD

**Issue by skybaks** [openplanet-nl/issues#20]
I would like to be able to define a preprocessor variable global to my plugin but simply putting it in one code file does not consistently apply the definition to all my files.

My suggestion is to add an entry to the info.toml file like so:
```
[script]
defines = [ "MY_VAR1", "MY_VAR2" ]
```

**Comment by skybaks** [comment]
While this would be nice to have, I consider it a low priority because I have what seems to be a functional workaround. I created a file at a path that I think will be read in first by the compiler and put my defines in there.

**Comment by codecat** [comment]
What do you need this for?

**Comment by skybaks** [comment]
I have set up a "unit testing" of sorts system inside the presets plugin I am currently working on. Using a UNIT_TEST preprocessor define I compile in different plugin settings and also run a suite of tests to check my serialization and deserialization methods.
I dont want users to have to deal with my testing settings in the released plugin but I would like to keep them in the code for my development.

**Comment by skybaks** [comment]
It works exactly as I hoped. Thank you! @codecat
