### ISSUE TITLE
Add an argument to Dev::Hook() to specify which registers it should preserve

### ISSUE THREAD

**Issue by Miltant** [openplanet-nl/issues#21]
As of now, only a bunch of registers are backed up and restored by the instructions wrapping a hook's function call.
It practically limits what addresses can be hooked, and it makes writing non-bugged angelscript hook function quite hard.
So I would greatly appreciate some way to tell the Dev api which registers I would like it to preserve for me, as I understand that allocating space for all registers would be too expensive to be a default behavior.

**Comment by codecat** [comment]
Specifically, the registers that prompted this issue are xmm registers (which are large)
