### ISSUE TITLE
Improve IO::File API

### ISSUE THREAD

**Issue by nitroquery** [openplanet-nl/issues#23]
imo `IO::File ` API lacks of some features.

e.g.

- [ ] void `.Sync()` || `.Flush()`   
Considering that TM is game which likes to crash a lot then there can be critical use cases where file buffers should Synced to disk. Unaware of current API implementation im not sure which approach would be best for the API considering performance and data integrity. Would it be enough to have `.Flush` to copy data from the internal buffer to the operating system buffer or should it be `Sync` as syscall to fsync to write data out?
- [ ] .Truncate() ?

anything else?

**Comment by codecat** [comment]
I don't think `Sync()` and `Truncate()` are necessary, but I have added `Flush()`.
