### ISSUE TITLE
Make strings selectable and copiable when Nods are accessed through the Scene Explorer

### ISSUE THREAD

**Issue by Atheuz** [openplanet-nl/issues#3]
Use case:
OpenPlanet finds Manialink pages through the scene explorer, that then can be viewed in the Nod explorer, but the actual location of the Manialink page in the Nod tree is not really known, and so it's not really accessible through code. 
Then, if you want to copy the value of strings such as `ScriptText` programmatically you can't do that because you can't find the page.
What would alleviate this problem is if the value of fields are selectable and copiable manually, but this is not currently possible when you're accessing Manialink pages found through the scene explorer, while it does seem possible to do so when you're in the normal Nod explorer, though it's not often that you can find these in the Nod explorer and you're dependent on the Scene explorer

Through the Nod explorer:
![billede](https://user-images.githubusercontent.com/202696/135926587-73f88491-b066-4cc0-bbf4-fc4a8aff7e06.png)

Through the Scene explorer:
![billede](https://user-images.githubusercontent.com/202696/135926534-945366d0-e7f1-4629-88a3-686e873daf90.png)

Would it be possible to make strings like these selectable and copiable?

**Comment by codecat** [comment]
I've implemented it like this:

![image](https://user-images.githubusercontent.com/136534/136194592-8086ccfe-f14b-4b84-b67b-56b3b5ffcf54.png)

**Comment by Atheuz** [comment]
Nice. That'll work, thank you.
