### ISSUE TITLE
Some mouse/keyboard events not captured

### ISSUE THREAD

**Issue by Phlarx** [openplanet-nl/issues#30]
I noticed a few actions do not trigger a callback (e.g. `OnKeyPress`):
- The `Alt` key (maybe `AltGr`, too, but I don't have that on my keyboard to test)
  - There is no (obvious) mapping in the `VirtualKey` enum for these
- Mouse scroll events
  - Tested up / down / left / right
  - No mapping in `VirtualKey`, and the `OnMouseButton` callback only has a `int button` id, so there's no obvious way to even receive these events

Unknown if these are limitations of Openplanet, Nadeo, imgui, or something else.

**Comment by codecat** [comment]
I've fixed this for the next update.

For Alt, you are looking for `VirtualKey::Menu` (`VK_MENU`).

The new callback signature for mousewheel events is:
```asc
bool OnMouseWheel(int x, int y)
```

I guess technically I could change the `int` to an enum, but that's for a later refactor. For now, you can safely assume that the button numbers will never change:
* 0 = left mouse button
* 1 = right mouse button
* 2 = middle mouse button

Note that currently any additional mouse buttons are not supported.. open another Github issue for that if you need it!

**Comment by Phlarx** [comment]
Are the x and y parameters to `bool OnMouseWheel(int x, int y)` the scroll input value or the mouse position?

**Comment by codecat** [comment]
It's the scroll delta in a direction, x being horizontal and y vertical. It's in segments of 120 (or less, when using smooth scrolling via eg. an Apple Magic Trackpad.
