### ISSUE TITLE
Add IO::FromUserFolder

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/issues#33]
Actually to have access to the user folder we had to get from `Fids::GetUserFolder()` then iterate to get the full directory path we want through `CSystemFids`. A better solution would be using `IO` to get directly the user directory path

**Comment by codecat** [comment]
To be more precise, `C:/Users/Username/Documents/Trackmania` (or whatever the game's user folder is currently set to)

**Comment by codecat** [comment]
I've added this as `IO::FromUserGameFolder`.
