### ISSUE TITLE
Dialogs::Question can't get Class properties

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/issues#34]
Context:
```angelscript
class MyClass {
    array<string> MyStrings;

   void DoThis()
   {
        Dialogs::Question("Are you sure?", function(){
             MyStrings.InsertAt(0, "something");
             MyStrings.InsertAt(0, "another string");
             print("Added");
        }, function(){
            print("do nothing here");
        });
   }
}

void Main()
{
    MyClass theClass = MyClass();
    theClass.DoThis();
}
```

Excepted:
Should opens a question dialog with the "are you sure" and adds the strings to the array

Actual:
`ERR: No matching symbol 'MyStrings'`

PS: Dialogs.as is already imported

**Comment by codecat** [comment]
As per the [Angelscript documentation](https://www.angelcode.com/angelscript/sdk/docs/manual/doc_script_anonfunc.html):

> It is not yet possible for anonymous functions to access variables declared in the same scope as the function, i.e. they cannot be used as closures.

You might be able to do this however, but I have not tested it:

```asc
class MyClass {
  array<string> m_myStrings;

  void ButtonPressed() {
    m_myStrings.InsertLast("Hello");
  }

  void DoThis() {
    Dialogs::Question("Are you sure?", OnButtonPress(ButtonPressed));
  }
}
```
