### ISSUE TITLE
Game/OpenPlanet Crashes on Defining Settings

### ISSUE THREAD

**Issue by haseeb-heaven** [openplanet-nl/issues#35]
Hi,
The game and **Openplanet** crashes if you define settings with having space _-->` `<--_ in between keyword.
Example:

**_CRASHES HERE_**
[Setting category="General" name = "Show Plugin"] --> Notice space after keyword **name** 

**_FIXED HERE_**
[Setting category="General" name="Show Plugin"] --> Notice No space after keyword **name** 

Some info from Logs to Help.

**_[Platform] [22:02:25]  Versions:
[Platform] [22:02:25]    ManiaPlanet2021-12-03 16:12:50
[Platform] [22:02:25]    Openplanet  1.21.0 (next, Public, 2021-12-16)
[Platform] [22:02:25]  Game version: 2021-12-03_**

**Comment by codecat** [comment]
Hmm, I can't reproduce this crash with the following test plugin:

```asc
[Setting name = "aa"]
bool Setting_Test;
```

Nor do I see anything wrong in the code execution flow.

Do you have a reliable reproduction Are you sure it's because of that piece of code? What happens if you disable every other plugin and only load the plugin with the bug?

**Comment by codecat** [comment]
Also, what type of setting was this? A boolean? A string? A number?

**Comment by haseeb-heaven** [comment]
> Also, what type of setting was this? A boolean? A string? A number?

It was of Type boolean, 
```
[Setting category="General" name="Show Plugin"] 
bool Setting_ShowPlugin = false;
```

**Comment by haseeb-heaven** [comment]
> Hmm, I can't reproduce this crash with the following test plugin:
> 
> ```c++
> [Setting name = "aa"]
> bool Setting_Test;
> ```
> 
> Nor do I see anything wrong in the code execution flow.
> 
> Do you have a reliable reproduction Are you sure it's because of that piece of code? What happens if you disable every other plugin and only load the plugin with the bug?

Can you check with this example [Plugin_Test](https://pastebin.com/XXXL8iHY) ? Try to test it with newly opened game

Or try this example:
`[Setting category = "Shortcuts" name = "Show/Hide Key"] VirtualKey Setting_ShowUiKey = VirtualKey::F5;`
In one line no new line between them.
