### ISSUE TITLE
Possibility to add `IO::GetClipboard`

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/issues#41]
We can set strings with `IO::SetClipboard()`, but we can't get contents from a clipboard. Would be useful for copying a content and checks if it was copied (string must corresponds)

**Comment by codecat** [comment]
This always seems like a scary API to implement. I know there are legit reasons to have this API, but this would also allow a plugin to silently spy on someone's clipboard as well. A possible solution to this would be to make `GetClipboard` return an empty string when the game window is not focused, but I'm not sure how much that would really help.

Discussion welcome.

**Comment by GreepTheSheep** [comment]
Your solution seems good for me :+1:

**Comment by RuurdBijlsma** [comment]
maybe only allow getclipboard when the clipboard value was set while in game, either from ctrl c or SetClipboard

**Comment by codecat** [comment]
> maybe only allow getclipboard when the clipboard value was set while in game, either from ctrl c or SetClipboard

Late reply, but I think this would diminish the usefulness of this API quite a bit.

Greep, is this still something you need for a plugin? Curious about your use case.

**Comment by GreepTheSheep** [comment]
Tbh I don't remember for my use case 😂
It was for autofill an input but ctrl+v is better

**Comment by codecat** [comment]
I will close this for now then. If anyone has a good use case, feel free to re-open 😊
