### ISSUE TITLE
No 'scripts' tab in the ingame openplanet ui

### ISSUE THREAD

**Issue by n-garc** [openplanet-nl/issues#419]
When I open trackmania there is no 'scripts' tab in the openplanet UI.

![tm_openplanet](https://github.com/openplanet-nl/issues/assets/98439831/67c26e98-20b4-444c-af7e-016861a83744)

    Version: 1.26.9
    Game: TM2020

**Comment by XertroV** [comment]
It was renamed to "Plugins" a few versions ago.

Also be advised that 1.26.9 doesn't work correctly with the latest version of TM2020. You should use 1.26.12

**Comment by codecat** [comment]
Did you read somewhere there's a "Scripts" menu? That page will have to be updated.

**Comment by n-garc** [comment]
The trackmania exchange random map picker plugin documentation still refers
to a scripts tab. I originally posted this issue there. It seems the real
issue is that that plugin seems to require club access.
