### ISSUE TITLE
Assertion failed when trying to set a flag to a boolean

### ISSUE THREAD

**Issue by thaumictom** [openplanet-nl/issues#45]
The following code

```cpp
#name "MyTest"
#author "ThaumicTom"
#category "None"

void RenderInterface()
{
	if (UI::Begin("Interface")) {
		if (UI::BeginTable("Table", 1, UI::TableFlags::SizingFixedFit = true | UI::TableFlags::Hideable | UI::TableFlags::RowBg)) {
			//                                                    ^^^^^^
			UI::TableSetupColumn("This is a column", 0, 10);
			UI::TableHeadersRow();

			for (uint i = 0; i < 5; i++) {
				UI::TableNextRow();
				UI::TableSetColumnIndex(0);
				UI::Text("Test");
			}

			UI::EndTable();
		}
	}
	UI::End();
}

void Main()
{
	RenderInterface();
}
```

returns the following error

![image](https://user-images.githubusercontent.com/15818698/148272427-9911ad53-f350-48ec-953b-94b82f5b35ff.png)

It is ignoreable - but you have to press Ignore four times. The code is obviously illegal and a syntax error but it still causes the compiler problems.

Openplanet for Turbo (1.21.0)

**Comment by codecat** [comment]
Bug filed: https://www.gamedev.net/forums/topic/711744-assertion-failed-on-invalid-use-of-enum-bit-flags/

**Comment by codecat** [comment]
I'll close this issue for now considering the bug is in Angelscript and the issue was reported there.
