### ISSUE TITLE
Optional plugin dependencies

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/issues#55]
[Link to discord message for reference](https://discord.com/channels/276076890714800129/424967293538402334/937469448619692085)

Possibility to set parameters to the preprocessor to check if a dependent plugin is installed. I want for example to tell a button to do an action to another plugin only if this plugin is installed, otherwise it does something else, without crashing and saying that the dependent plugin did not exists

**Comment by codecat** [comment]
I have implemented this using a new key `optionaldependencies` in `info.toml`:

```toml
[script]
optionaldependencies = [ "Depper" ]
```

This will make a preprocessor definition called `DEPENDENCY_DEPPER` (depending on the dependency ID, where spaces are changed to underscores if there are any).

```asc
#if DEPENDENCY_DEPPER
	Depper::Hello();
#else
	print("Depper not installed");
#endif
```

This leaves `dependencies` as a list of required plugins. This changes previous behavior where missing dependencies would still compile and run the plugin, but I don't expect that would cause too many problems. It will now throw a proper error, too:

![image](https://user-images.githubusercontent.com/136534/153765646-e725f28a-7c4f-44a7-887a-4a9e1e486445.png)
