### ISSUE TITLE
Icons of default font only render if `nvg::FontFace` is called before

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/issues#57]
I appears that rendering Icons using `nvg::Text` with the default font only works when you load the default "DroidSans" font explicitly and set it using `nvg::FontFace`.

(top left corner of image is for comparison)
![grafik](https://user-images.githubusercontent.com/28757333/152170548-dc3351cd-54e7-471a-9942-18e2756fa6aa.png)

**Comment by Nsgr** [comment]
Even with the nvg::FontFace, in TM2, Icons seem to not get rendered aswell

**Comment by codecat** [comment]
![image](https://user-images.githubusercontent.com/136534/152814458-dc9c249d-5df6-420e-8999-c342c608cecb.png)

I've fixed this for the next update.
