### ISSUE TITLE
Allow for copying text from the ingame log window

### ISSUE THREAD

**Issue by CatzHoekk** [openplanet-nl/issues#59]
Would be neat if we could copy text from the log window. Benefits should be obvious.

Should be possible with a UI::InputTextMultiline flagged with UI::InputTextFlags::ReadOnly

**Comment by CatzHoekk** [comment]
> Nsgr: Could also use the IsItemHovered Method and display a tooltip for "text will be copied when clicked"

Maybe the idea is also good inspiration to maybe get the whole log easily? A context menu maybe?

**Comment by codecat** [comment]
It might be nice as well to add an "Open Openplanet.log" to the menu of the log window which opens the log file in Notepad.

**Comment by codecat** [comment]
![image](https://user-images.githubusercontent.com/136534/152816773-696ff7b2-362a-4587-93c0-ce8019829234.png)

Perhaps this will suffice?
