### ISSUE TITLE
"Assertion failed" when trying to load any plugin

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/issues#60]
When I try to download and load a plugin through the Plugin Manager, this error comes and crashes the game:
![image](https://user-images.githubusercontent.com/42576124/152595645-1abe9fb5-4f61-43b3-b9c1-2275ee6d975f.png)

Actually it:
1. Downloads and place the plugin in the "Plugins" folder as excepted.
2. But when it loads, this error comes.

It's not always from the Plugin Manager: this comes too when initializing Openplanet on game start, witch it's more serious

**Comment by codecat** [comment]
Angelscript bug filed here: https://www.gamedev.net/forums/topic/711782-signed-stack-offset-causes-failed-assertion-when-compiling-global-variables

I have implemented a temporary fix as described in the linked thread, but it's not a good long term solution.

**Comment by codecat** [comment]
The bug was fixed in Angelscript by changing `stackOffset` to a 32 bit integer. Additionally, I am making it so `Icons.as` is included in Openplanet itself, so it doens't need to be included manually, doesn't pollute the global namespace, and doesn't slow down plugin compilation. Nice! 👍
