### ISSUE TITLE
False Positive on VirusTotal 

### ISSUE THREAD

**Issue by IcyTv** [openplanet-nl/issues#63]
The latest build of OpenPlanet is detected on VirusTotal by 4 Antivirus programs. [See Here](https://www.virustotal.com/gui/file/18ea68c7897d3935345ced83d6760ecff218b5d8611ea7bd274fb7bcfef92bec/detection)

As far as I can tell (from the bit of googling I did), this is quite a common false positive. This isn't the end of the world, but maybe something can be done.

**Comment by codecat** [comment]
Yeah this is not something I can control. Your best bet is to submit it as a false positive and have those companies fix the problem. I generally don't do this myself because if I did I'd be wasting a lot of my own time doing this every update 😄 

Thanks for the report though!
