### ISSUE TITLE
Stopping click propagation in OnMouseButton does not work on initial plugin load

### ISSUE THREAD

**Issue by RuurdBijlsma** [openplanet-nl/issues#71]
When returning true from the OnMouseButton callback, the click is not supposed to propagate further, however, on the first load of a plugin it does. After any subsequent reloads it does work, and properly stop the click from going through.

`main.as` Code to reproduce: 
```
bool OnMouseButton(bool down, int button, int x, int y) {
    print("{" + x + ", " + y + "}, down: " + down + ", button: " + button);

    if(x < 1000 && down && button == 0) {
        print("Returning true");
        return true;
    }
    print("Returning false");
    return false;
}
```

In this code, if you click in the left 1000 pixels on the screen it's supposed to stop the click from going through. Works fine, except on first load after game startup.

Video of bug happening: https://youtu.be/X-nFNAyyOXs 

The click on map editor is supposed to be stopped, then I reload the plugin, and it stops clicks properly.

**Comment by codecat** [comment]
Thanks, this should be fixed in the next update!
