### ISSUE TITLE
EventType is not accessible from CSceneVehicleVisState.

### ISSUE THREAD

**Issue by RoadToLP** [openplanet-nl/issues#72]
`EventType`, while is member of `CSceneVehicleVisState`, according to [documentation](https://next.openplanet.dev/Scene/CSceneVehicleVisState), is inaccessible from scripts.
Example:
```
void Main(){
	CSceneVehicleVisState@ state = VehicleState::ViewingPlayerState();
	print(state.EventType);
}
```
Produces `ERR : 'EventType' is not a member of 'CSceneVehicleVisState'` error in Openplanet logs.

**Comment by codecat** [comment]
This is intended, though I might have to hide this from the documentation. The property is described, but it has no valid offset within the structure, and there is no virtual function to call to get or set its value.

Either Nadeo didn't correctly implement this property, it doesn't even within the object, or the property is only defined for some specific networking or serialization purpose.

Either way, the property is not accessible.

**Comment by codecat** [comment]
I'll close this for now since it's not really an Openplanet bug.
