### ISSUE TITLE
Problem with update

### ISSUE THREAD

**Issue by PolskiGlizda** [openplanet-nl/issues#77]
While openplanet tries to update from 1.22.4 to 1.22.9 I get an "error opening file for writing: C:\Progam Files (x86)\Ubisoft\Ubisoft Game Launcher\games\Trackmania\Openplanet.dll" and the same for dinput8.dll, I got it on my windows 10 machine and walked around it by reinstalling openplanet but on my linux machine I can't get it to work. I use lutris(with lutris-fshack-6.21-6-x86_64 as a runner) to launch the ubisoft connect and run TM from there, before 31.03.2022 everything worked fine but after last update it stoped.

**Comment by codecat** [comment]
Make sure the game is closed when you update.

**Comment by PolskiGlizda** [comment]
That worked thank you so much I feel stupid now. When I updated before it worked with game running so I haven't even thought about it
