### ISSUE TITLE
Opening a file with FileSource does not work when that file is in a folder

### ISSUE THREAD

**Issue by RuurdBijlsma** [openplanet-nl/issues#79]
Loading a file from root works:
```
print("Reading `info.toml`:");
IO::FileSource file("info.toml");
print(file.ReadToEnd());
```
Loading a file in a folder does not:
```
print("Reading `folder/info.toml`:");
IO::FileSource folderFile("folder/info.toml");
print(folderFile.ReadToEnd());
```

![image](https://user-images.githubusercontent.com/5478546/161535058-5b4ccbf9-7dff-4f3c-b704-7d46e97e3d79.png)

Reproduction plugin: 
[FSB.zip](https://github.com/openplanet-nl/plugin-manager/files/8409213/FSB.zip)

**Comment by codecat** [comment]
How did you make this zip? There are backslashes in the zip entries, which I believe is technically invalid in the zip standard.

**Comment by RuurdBijlsma** [comment]
The .op zip i made with powershell

```ps
$compress = @{
    Path = "./info.toml", "./src", "./folder"
    CompressionLevel = "Fastest"
    DestinationPath = "../temp.zip"
}
Compress-Archive @compress -Force
```

the outer zip just with windows right click compress to zip

**Comment by RuurdBijlsma** [comment]
Just tested by making the .op file with windows zip functionality, that works wow.

**Comment by codecat** [comment]
This is a [known issue in Powershell](https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/71) and you should update to the latest version of `Microsoft.PowerShell.Archive`.
