### ISSUE TITLE
Constructors are missing from the docs

### ISSUE THREAD

**Issue by Phlarx** [openplanet-nl/issues#80]
For example, https://openplanet.dev/docs/api/IO/File is missing any indication of the invocation:
```asc
IO::File myFile('data.txt');
```

**Comment by codecat** [comment]
![image](https://user-images.githubusercontent.com/136534/161727121-143a46f6-f0ec-418c-90f6-6d304c71d075.png)

Thanks, I will add this to the next site update soon! 👍 

Edit: this is now deployed.
