### ISSUE TITLE
[Game crash] Attempting to get a list of MapList_Names

### ISSUE THREAD

**Issue by chipsTM** [openplanet-nl/issues#85]
For some reason calling this code (which appears to be correct) causes the game to crash with no explanation of the root cause.

```
void Main() {
#if TMNEXT
    auto app = cast<CTrackMania>(GetApp());
    auto network = cast<CTrackManiaNetwork>(app.Network);

        if (network.PlaygroundInterfaceScriptHandler !is null && network.PlaygroundInterfaceScriptHandler.Playground !is null) {
            auto maps = network.PlaygroundInterfaceScriptHandler.Playground.MapList_Names;
        }
#endif
}
```

I assume the expected behavior would be either an empty array/buffer (if in game menus) or a array/buffer of `wstring`s with the map names.

**Comment by codecat** [comment]
I believe this is not valid code actually; perhaps `MapList_Names` can't be considered valid unless `MapList_Request()` is called. Then you also need to wait for `MapList_IsInProgress`. (You can find a reference implementation in Maniascript in `PauseMenuOnline_Client.Script.txt`)

Additionally, `MapList_Names` and `MapList_MapUids` share the same block of memory (despite both using a different string type), which seems wrong. The Maniascript that uses these properties also never use `MapList_Names`, and only use `MapList_MapUids`.
