### ISSUE TITLE
CHmsCamera.m_isOverlay3d weird behaviour when setting via script

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/issues#87]
My game crashes when setting back a CHmsCamera property to what it was before I set it to true.

I attached an example plugin to have a menu option to change the cameras when you click it, wait 5 seconds and change them back:
[YEPCameras.zip](https://github.com/openplanet-nl/issues/files/8463659/YEPCameras.zip)

**Comment by codecat** [comment]
Looks like a crash deep inside of Trackmania's code, either way doesn't look like it has much to do with Openplanet. The only thing I can think could be a difference is when this property is set back to false, it's the wrong time (eg. it must be done during rendering).
