### ISSUE TITLE
1.23.0 cant install

### ISSUE THREAD

**Issue by propork** [openplanet-nl/issues#89]
Closing the game before pressing "install update" closes the first installer, and opening the second installer force closes the game and Openplanet.dll and dinput8.dll won't write.

**Comment by codecat** [comment]
Even when the game is 100% closed and you clicked "Retry"?

I've just made a change to the installer for the next updates that force closes the game when installing. That might help with these confusions.

**Comment by codecat** [comment]
Assuming that was indeed the issue, I will close this for now. Let me know if you still have problems with this! You can also always ask [on Discord](https://openplanet.dev/link/discord).
