### ISSUE TITLE
Dependent plugin not reloaded when dependency plugin is installed

### ISSUE THREAD

**Issue by MKuijpers** [openplanet-nl/issues#90]
When using a dependency plugin (either required or optional), the dependent plugin is not reloaded when the dependency plugin is installed, while the dependent plugin is reloaded whenever the dependency plugin is uninstalled.

It can be reproduced with a simple example (including `info.toml` file specifying a required or optional dependency):

```angelscript
void Render()
{
#if DEPENDENCY_...
    print("foo");
#endif
}
```

If you start with the dependency plugin installed and uninstall it, 'foo' will stop printing. (correct behavior)
However, if you start with the dependency plugin uninstalled, and install it, 'foo' will not start printing. (wrong behavior)

**Comment by codecat** [comment]
I've fixed this for the next update.
