### ISSUE TITLE
Dynamically set execution timeout for plugins to accomplish certain tasks

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/issues#91]
I'm writing a plugin where I index and parse all files in the user's Map folder (recursively). Depending on storage speed, amount of files in the folder etc. this could take longer than the default script execution timeout, and by a varying amount per user.

For this, I propose a method that could enable a plugin to temporaily modify it's execution timeout, which could look something like this:
```angelscript
uint pluginExecutionTimeout = Meta::ExecutingPlugin().get_Timeout();
Meta::SetExecutionTimeout(Meta::ExecutingPlugin(), 0);
string[] foundFiles = IO::IndexFolder(userGameFolderPath + "Maps", true); // Indexes all files recursively in Maps folder

// Parsing...

Meta::SetExecutionTimeout(Meta::ExecutingPlugin(), pluginExecutionTimeout);
```

**Comment by codecat** [comment]
Instead of a specific execution timeout, what about a helper class that disables it until the instance is destroyed? For example:

```angelscript
void Something()
{
  Meta::DisableExecutionTimeout det;
  // .. do stuff
  // at the end of the scope, `det` is autmatically destroyed
}
```

**Comment by Nsgr** [comment]
For my purpose, that would also work!

I don't know if I would ever encounter a situation where I can't yield and still want to cut off the execution after a specific timeout. So if it's easier to implement the scoped solution for now and wait for another issue when that situation might arise, definitely go for it.

**Comment by codecat** [comment]
I will not be adding this, as it will add unnecessary complexity to the script runtime. The better solution is to either increase the timeout in `info.toml` or to set it to 0 and make sure you never accidentally write infinite loops.

The main reason for this is that the timeout is achieved by setting a callback on Angelscript's execution context, and testing aborting execution when it reaches the limit. Turning this off temporarily at runtime adds a lot of complexity that I'd rather want to avoid. The callback adds some overhead as well, so it will be better to just set it to 0 in your info file.

If you still think you need this, lemme know and maybe we can figure something out that makes sense, but as it stands, I don't see any benefit of having this over just setting the timeout to 0 (or increasing it).
