### ISSUE TITLE
Possibility to add `IO::DeleteFolder()`

### ISSUE THREAD

**Issue by GreepTheSheep** [openplanet-nl/issues#92]
Hi,

Currently it is not possible to delete a folder with Openplanet.
I would like to implement this because currently my custom skids installation plugin can delete them, but the game can't reload the mod (even when restarting it) because there is a ModWorks folder (even empty). Which causes confusion

**Comment by codecat** [comment]
I am actually kinda against this, because I think this might cause some people to accidentally delete their entire user folder by mistake. I might implement this with heavy restrictions.

**Comment by codecat** [comment]
I've implemented this with a couple safety checks. For example, the following will throw an exception:
```angelscript
IO::DeleteFolder(IO::FromDataFolder(""), true);
```
Additionally, the second parameter means `recursive`, and can be omitted to default it to `false`. When it is false, only empty directories can be deleted. (In which case, the safety checks are not ran.)
