### ISSUE TITLE
`IO::CreateFolder` with `recursive = true` is not recursive

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/issues#93]
Example call:
`IO::CreateFolder("C:/Users/xyz/Documents/Trackmania/Scripts/SubFolder1/SubFolder2/SubFolder3", true)`

While only "Scripts" is an existing folder.
The subfolders do not get created, instead if just works if everyhting until exclusive "SubFolder3" is already there.

**Comment by codecat** [comment]
This function apparently only worked with backslashes. I've fixed this for the next update.
