### ISSUE TITLE
`IO::File` does not throw an error if it cannot be created due to missing folder

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/issues#94]
Example call:
```angelscript
IO::File destFile("C:/Users/xyz/Documents/Trackmania/Scripts/SubFolder1/SubFolder2/SubFolder3/File.txt", IO::FileMode::Write);
destFile.Write(sourceFile);
destFile.Close();
```
(...while nothing past the "Scripts" folder exists)

Nothing happens and no error is thrown.

**Comment by codecat** [comment]
Scripts will now throw an exception as soon as files cannot be opened: `Unable to open file with the desired mode.`
