### ISSUE TITLE
Be able to verify plugin integrity with something the likes of `Meta::Plugin::get_Signed()`

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/issues#95]
I'm making a plugin that is supposed to be club-only, but I still want to be sure it hasn't been tampered with as it might be used in a semi-competitive environment.

Another plugin will use Exports of this plugin, and is likely required to check that the plugin is working correctly AND hasn't been tampered with to get a competitive advantage. For that, I suggest adding something like `Meta::Plugin::get_Signed()` to check for plugin integrity, and I would add Permissions.as checks to the plugin to still restrict it to Club edition.

**Comment by codecat** [comment]
I'm not sure how this would help if someone could just remove the check.

**Comment by Nsgr** [comment]
That's definitely true🤔

**Comment by codecat** [comment]
I don't think doing this will be possible at all unfortunately, so I'll close this issue.
