### ISSUE TITLE
Add Openplanet version getter in `Meta` API

### ISSUE THREAD

**Issue by Nsgr** [openplanet-nl/issues#96]
Related to #94 , I would like to add a check whether I can expect this issue to be solved or not in my plugin.

One way to accomplish that is to check for the Openplanet version - since my plugin would likely compile on both new and old versions, I couldn't be sure without it. Maybe for sutff like my exact issue there is a workaround, but I could imagine a similar situation without one where this will come in handy.

**Comment by codecat** [comment]
This exists already: `Meta::OpenplanetVersion()`, `Meta::OpenplanetVersionDate()`, `Meta::OpenplanetBuildInfo()`.
